### ISSUE TITLE
warning/error displayed on opening heroku link

### ISSUE THREAD

**Issue by pratik-choudhari** [jmrchelani/scrap-this-web#2]
When I open the heroku link this text is displayed, is it supposed to be like this?
__Cannot read property 'indexOf' of undefined__

**Comment by jmrchelani** [comment]
Well, thanks for looking into it and opening an issue.
This is happening because there is no check for null url. like you visit the heroku page without adding a URL request then it has no url resulting in that error.
I will fix this soon.

**Comment by jmrchelani** [comment]
Well, Now if you just open the heroku link without URL provided as GET - It will redirect to the repo.
Hence, I guess this is fixed.
Thanks for your help, cheers.
